"""create rule tables

Revision ID: e87df8b344b7
Revises:
Create Date: 2025-12-26 14:50:31.224807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e87df8b344b7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("min_income", sa.Float(), nullable=True),
        sa.Column("multiplier", sa.Integer(), nullable=True),
        sa.Column("rate", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tier"),
    )
    op.create_table(
        "risk_level_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("state_risk", sa.String(), nullable=False),
        sa.Column("min_credit_score", sa.Integer(), nullable=False),
        sa.Column("max_dti_ratio", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "state_risk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state"),
    )
    op.create_table(
        "unserviceable_pins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pin_code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pin_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unserviceable_pins")
    op.drop_table("state_risk")
    op.drop_table("risk_level_rules")
    op.drop_table("city_rules")
    # ### end Alembic commands ###
