"""create loan tables

Revision ID: dc86550b94b4
Revises: 
Create Date: 2026-01-05 17:03:28.573294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc86550b94b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rules',
    sa.Column('rule_key', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rule_key')
    )
    op.create_index(op.f('ix_business_rules_rule_key'), 'business_rules', ['rule_key'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bureau_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('employment_duration_months', sa.Integer(), nullable=True),
    sa.Column('existing_debt', sa.Float(), nullable=True),
    sa.Column('loan_requested', sa.Float(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('city_tier', sa.String(), nullable=True),
    sa.Column('pin_code', sa.String(length=6), nullable=True),
    sa.Column('disaster_affected_area', sa.Boolean(), nullable=True),
    sa.Column('address_duration_months', sa.Integer(), nullable=True),
    sa.Column('work_location_matches_residence', sa.Boolean(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('risk_assessment', sa.String(), nullable=True),
    sa.Column('interest_rate', sa.String(), nullable=True),
    sa.Column('decision_metadata', sa.JSON(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_pan_number'), 'loans', ['pan_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_pan_number'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_business_rules_rule_key'), table_name='business_rules')
    op.drop_table('business_rules')
    # ### end Alembic commands ###
